orbs:
  wpengine: ryanshoover/wpengine@0.7.2
version: 2.1
workflows:
  test-deploy:
    jobs:
      - wpengine/build
      - wpengine/lint:
          requires:
            - wpengine/build
      - wpengine/codeception:
          package_name: post-mark-as-read
          package_type: plugin
          requires:
            - wpengine/build
      - wpengine/deploy_fury:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          requires:
            - wpengine/lint
            - wpengine/codeception
  version: 2