# PHP CircleCI 2.1 configuration file
# See: https://circleci.com/docs/configuration-reference/
version: 2.1

# Define the jobs
jobs:
  build-and-test:
    docker:
      - image: cimg/php:7.4
    
    working_directory: ~/wp_plugin
    
    steps:
      - checkout
      
      # Install system dependencies
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y zlib1g-dev libsqlite3-dev
            sudo docker-php-ext-install zip
      
      # Restore cached dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "wp-content/plugins/post-mark-as-read/composer.json" }}
            - v2-dependencies-
      
      # Install composer dependencies
      - run:
          name: Install composer dependencies
          command: |
            cd wp-content/plugins/post-mark-as-read
            composer install -n --prefer-dist --no-progress
            composer update -n --no-progress
      
      # Save dependency cache
      - save_cache:
          key: v2-dependencies-{{ checksum "wp-content/plugins/post-mark-as-read/composer.json" }}
          paths:
            - wp-content/plugins/post-mark-as-read/vendor
      
      # Run PHPUnit tests
      - run:
          name: Run PHPUnit tests
          command: |
            cd wp-content/plugins/post-mark-as-read
            ./vendor/bin/phpunit --colors=always --verbose
      
      # Store test results
      - store_test_results:
          path: wp-content/plugins/post-mark-as-read/test-results
      
      # Store artifacts
      - store_artifacts:
          path: wp-content/plugins/post-mark-as-read/test-results
          destination: test-results

# Define workflows
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
