name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: wp-content/plugins/post-mark-as-read

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, xml, zip
        coverage: none

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress
        composer update --no-progress
    
    - name: Validate composer files (after update)
      run: composer validate --strict

    - name: Run test suite
      run: ./vendor/bin/phpunit --colors=always
